import os
from langchain_community.vectorstores import Chroma
# [FIXED] Updated to use the dedicated langchain_huggingface package
from langchain_huggingface import HuggingFaceEmbeddings
from langchain.tools import tool

# =====================================================================
# CONFIGURATION
# =====================================================================
# Using the Vietnamese BI-Encoder optimized for native language understanding.
EMBEDDING_MODEL_NAME = "bkai-foundation-models/vietnamese-bi-encoder"
CHROMA_DB_DIR = "./data/vietnamese_med_corpus/chroma_db"

def get_vietnamese_vector_db() -> Chroma:
    """
    Initializes the embedding model and connects to the local Chroma database.
    """
    # 1. Initialize the HuggingFace Embedding model
    embeddings = HuggingFaceEmbeddings(
        model_name=EMBEDDING_MODEL_NAME,
        model_kwargs={'device': 'cuda'}, # Offload to T4 GPU
        encode_kwargs={'normalize_embeddings': True} # Required for cosine similarity
    )
    
    # 2. Connect to the local ChromaDB instance
    db = Chroma(
        collection_name="vietnamese_ehr_records",
        embedding_function=embeddings,
        persist_directory=CHROMA_DB_DIR
    )
    return db

@tool
def search_patient_records(query: str) -> str:
    """
    Use this tool to search for patient medical records (EHR), clinical notes, 
    allergies, and medical history from the localized Vietnamese Vector Database.
    
    Args:
        query (str): The search query or keywords generated by the reasoning LLM.
        
    Returns:
        str: A concatenated string of the most relevant medical documents.
    """
    try:
        print(f"🔍 [RAG Node] Executing semantic search for query: '{query}'...")
        
        db = get_vietnamese_vector_db()
        docs = db.similarity_search(query, k=3)
        
        if not docs:
            return "WARNING: No relevant medical data found in the patient records database."
            
        context = "\n\n--- RETRIEVED MEDICAL CONTEXT ---\n\n".join(
            [doc.page_content for doc in docs]
        )
        
        print("✅ [RAG Node] Successfully retrieved relevant medical history.")
        return f"Retrieved Context from Vietnamese EHR Database:\n\n{context}"
        
    except Exception as e:
        error_msg = f"CRITICAL ERROR retrieving RAG data: {str(e)}"
        print(f"❌ {error_msg}")
        return error_msg
